# Generated by Django 3.2.11 on 2022-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
