# Generated by Django 3.2.11 on 2022-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0002_pelicula_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='datePublished',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
