# Generated by Django 3.2.11 on 2022-01-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_rename_image_pelicula_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='datePublished',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='description',
        ),
    ]
