# Generated by Django 3.2.11 on 2022-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_auto_20220126_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genre',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='cast',
            field=models.CharField(help_text='Introduzca nombres separados por comas', max_length=250, verbose_name='casting'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='year',
            field=models.IntegerField(verbose_name='año'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='pelis.Genre'),
        ),
    ]
